# PAIRED (Platform for AI-Enabled Remote Development) Main Configuration
system:
  name: "PAIRED System"
  version: "1.0.0"
  environment: "development"
  
orchestration:
  claude_code:
    enabled: true
    timeout: 30000
    max_retries: 3
    token_optimization: true
  
  windsurf:
    enabled: true
    fallback_mode: true
    reasoning_threshold: 0.7
  
agents:
  auto_initialize: true
  max_concurrent: 10
  health_check_interval: 60000
  
memory:
  storage_path: "./data/memory"
  max_size_mb: 1000
  cleanup_interval: 3600000
  
logging:
  level: "info"
  file_path: "./data/logs/kf32.log"
  max_file_size: "10MB"
  max_files: 5
  
performance:
  monitoring_enabled: true
  metrics_interval: 30000
  alert_thresholds:
    response_time: 10000
    error_rate: 0.1
    memory_usage: 0.8
